### ISSUE TITLE
Handle Module Delete (Delete Logic File)

### ISSUE THREAD

**Issue by tiagomiguelcs** [SECURIoTESIGN/SAM#7]
When a module is flagged to be deleted, the logic file linked to that module should also be removed from the server. This should be implemented on the frontend (component [Module.js](https://github.com/SECURIoTESIGN/SAM/blob/master/src/components/Module.js)) and in the backend service (view [Module.py](https://github.com/SECURIoTESIGN/SAM-API/blob/master/views/module.py)).

**Comment by Chocowaffres** [comment]
A specific function to handle the deletion of the logic file solved this issue. Every time the administrator chooses to fully or partially delete the module, the logic file is also deleted.
